### ISSUE TITLE
Request page access

### ISSUE THREAD

**Issue by ChrisM-Git** [modernappsninjas/dojo#1]
Note: The contributor repository provides long-term storage of your assignments, contributions and ModernApps Ninja course completion records. It is a best practice to associate your records with a permanent account. If you are using a github account associated with your employer, you may prefer to use a personal github account to ensure you have permanent access to both your modernapps ninja records and your github contribution records in case you change employment in the future. You do not need any official or employer-associated account to request a contributor repository, participate in ModernApps Ninja activities or receive course completion certificates. 

If you are currently using an employer-associated github account and would prefer to use a personal account, do not complete this form. First, sign up for a personal github account, and login with your preferred account prior to completing this form. 

**Please enter the github ID of the user requesting the contributor repository**
Github_ID:ChrisM-Git

**Please enter the best email address to notify you once your contributor repository has been provisioned. This does not need to be the email address associated with your github account**
Email Address:
cmartin_@msn.com
---
You will only need to request a contributor repository one time, once you have one provisioned for you, you can use the repository for all future ModernApps Ninja assignment and course records. 

Please note that while we make our best effort to provision your contributor repository as quickly as possible, it could take up to a few days to provision the repo. However please be aware that requesting a contributor repo is a one-time process, once it is provisioned for you, it will be immediately usable for your ongoing needs.

Once we are able to review your request and provision your contributor repo, we will send an email to the provided email address with details and further instructions for accessing your contributor repository. 

Thank you for your contributions to the ModernApps Ninja Community!

**Comment by afewell** [comment]
Hi @ChrisM-Git  your repository is all setup and ready. You should see a link in the email account that is associated with your github account, to accept an invitation to become an administrator of your repo. You will need to accept that invitation to gain admin rights to your repo. 

Thanks!
